import React from "react";
import "./globals.css";
import { Provider } from "./api/auth/[...nextauth]/auth-providers";
import Header from "./components/Navbar";

export const metadata = {
  title: "Stack Shop",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header/>
          {children}
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout;
